# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{imexport}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 1.2") if s.respond_to? :required_rubygems_version=
  s.authors = ["alex"]
  s.date = %q{2009-04-21}
  s.description = %q{Simple import from a text file generated by mysql -E ...}
  s.email = %q{alex@digns.com}
  s.extra_rdoc_files = ["CHANGELOG", "lib/imexport.rb", "README.rdoc"]
  s.files = ["Rakefile", "imexport.gemspec", "Manifest", "CHANGELOG", "lib/imexport.rb", "README.rdoc"]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/crhym3/imexport}
  s.rdoc_options = ["--line-numbers", "--inline-source", "--title", "Imexport", "--main", "README.rdoc"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{imexport}
  s.rubygems_version = %q{1.3.2}
  s.summary = %q{Simple import from a text file generated by mysql -E ...}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
